# Generated by Django 4.0.8 on 2022-10-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_parameterset_part_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=100)),
                ('part_number', models.IntegerField(default=0, verbose_name='Part Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_parts', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Part',
                'verbose_name_plural': 'Parameter Set Parts',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='ParameterSetPartPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(default=0, verbose_name='Period Number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_parts', to='main.parametersetpart')),
            ],
            options={
                'verbose_name': 'Parameter Set Part Period',
                'verbose_name_plural': 'Parameter Part Periods',
                'ordering': ['period_number'],
            },
        ),
    ]
