# Generated by Django 4.0.8 on 2022-10-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_parametersetlabels_parametersetrandomoutcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPlayerPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set_labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_player_parts_c', to='main.parametersetlabels')),
                ('parameter_set_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_player_parts_b', to='main.parametersetpart')),
                ('parameter_set_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_player_parts_a', to='main.parametersetplayer')),
            ],
            options={
                'verbose_name': 'Parameter Set Player Part',
                'verbose_name_plural': 'Parameter Set Player Parts',
                'ordering': ['parameter_set_part'],
            },
        ),
    ]
