# Generated by Django 4.0.8 on 2022-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_parametersetplayerpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='period_length',
            field=models.IntegerField(default=20, verbose_name='Period Length, Production'),
        ),
        migrations.AlterField(
            model_name='parametersetrandomoutcome',
            name='abbreviation',
            field=models.CharField(default='NH', max_length=10),
        ),
    ]
