# Generated by Django 4.0.8 on 2022-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_parametersetrandomoutcome_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetpart',
            name='minimum_for_majority',
            field=models.IntegerField(default=7, verbose_name='Minimum for Majority'),
        ),
    ]
