# Generated by Django 4.0.8 on 2022-10-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_parametersetpart_minimum_for_majority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetlabelsperiod',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_labels_period_b', to='main.parametersetrandomoutcome'),
        ),
        migrations.AlterField(
            model_name='parametersetlabelsperiod',
            name='parameter_set_labels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_labels_period_a', to='main.parametersetlabels'),
        ),
    ]
