# Generated by Django 4.0.8 on 2022-10-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_parametersetlabelsperiod_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetlabelsperiod',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_labels_period_b', to='main.parametersetrandomoutcome'),
        ),
    ]
