# Generated by Django 4.0.8 on 2022-10-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_parameterset_label_set_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayerpart',
            name='group',
            field=models.IntegerField(default=0, verbose_name='Gruop Number'),
        ),
    ]
