# Generated by Django 4.0.8 on 2022-10-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_parametersetplayerpart_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetlabelsperiod',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_labels_period_b', to='main.parametersetrandomoutcome'),
        ),
    ]
