# Generated by Django 4.0.8 on 2022-10-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_parametersetplayerpart_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayerpart',
            name='parameter_set_labels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_player_parts_c', to='main.parametersetlabels'),
        ),
        migrations.AlterField(
            model_name='parametersetplayerpart',
            name='parameter_set_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_player_parts_b', to='main.parametersetpart'),
        ),
    ]
