# Generated by Django 4.0.8 on 2022-10-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_parametersetplayerpart_parameter_set_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetpartperiod',
            name='parameter_set_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_part_periods', to='main.parametersetpart'),
        ),
    ]
