# Generated by Django 4.0.8 on 2022-10-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_parametersetpartperiod_parameter_set_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetpart',
            name='pay_choice_majority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Pay if choice in majority choice'),
        ),
        migrations.AddField(
            model_name='parametersetpart',
            name='pay_choice_minority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Pay if choice in minority choice'),
        ),
        migrations.AddField(
            model_name='parametersetpart',
            name='pay_label_majority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Pay if label in majority choice'),
        ),
        migrations.AddField(
            model_name='parametersetpart',
            name='pay_label_minority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Pay if label in minority choice'),
        ),
    ]
