# Generated by Django 4.0.8 on 2022-10-13 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_parametersetpart_pay_choice_majority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetpartperiod',
            name='parameter_set_random_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_part_periods_b', to='main.parametersetrandomoutcome'),
        ),
        migrations.AlterField(
            model_name='parametersetpartperiod',
            name='parameter_set_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_part_periods_a', to='main.parametersetpart'),
        ),
    ]
