# Generated by Django 4.0.8 on 2022-10-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_parametersetpartperiod_parameter_set_random_outcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_parts', to='main.session')),
            ],
            options={
                'verbose_name': 'Session Part',
                'verbose_name_plural': 'Session Parts',
                'ordering': ['period_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionPlayerPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.IntegerField(default=0, verbose_name='Period Earnings')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_parts_a', to='main.sessionpart')),
                ('session_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_parts_b', to='main.sessionplayer')),
            ],
            options={
                'verbose_name': 'Session Player Part',
                'verbose_name_plural': 'Session Player Part',
                'ordering': ['session_player__session', 'session_player', 'session_part__period_number'],
            },
        ),
        migrations.RemoveField(
            model_name='sessionperiod',
            name='session',
        ),
        migrations.DeleteModel(
            name='SessionPlayerPeriod',
        ),
        migrations.AlterField(
            model_name='sessionplayerchat',
            name='session_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_chats_a', to='main.sessionpart'),
        ),
        migrations.DeleteModel(
            name='SessionPeriod',
        ),
        migrations.AddConstraint(
            model_name='sessionplayerpart',
            constraint=models.UniqueConstraint(fields=('session_player', 'session_part'), name='unique_session_player_period'),
        ),
        migrations.AddConstraint(
            model_name='sessionpart',
            constraint=models.UniqueConstraint(fields=('session', 'period_number'), name='unique_SD'),
        ),
    ]
