# Generated by Django 4.0.8 on 2022-10-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sessionpart_sessionplayerpart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPartPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Part Period',
                'verbose_name_plural': 'Session Periods',
                'ordering': ['session_part', 'parameter_set_part_period'],
            },
        ),
        migrations.AlterModelOptions(
            name='sessionpart',
            options={'ordering': ['parameter_set_part'], 'verbose_name': 'Session Part', 'verbose_name_plural': 'Session Parts'},
        ),
        migrations.AlterModelOptions(
            name='sessionplayerpart',
            options={'ordering': ['session_player', 'session_part'], 'verbose_name': 'Session Player Part', 'verbose_name_plural': 'Session Player Part'},
        ),
        migrations.RemoveConstraint(
            model_name='sessionpart',
            name='unique_SD',
        ),
        migrations.RemoveField(
            model_name='sessionpart',
            name='period_number',
        ),
        migrations.AddField(
            model_name='sessionpart',
            name='parameter_set_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_parts_b', to='main.parametersetpart'),
        ),
        migrations.AlterField(
            model_name='sessionpart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_parts_a', to='main.session'),
        ),
        migrations.AddConstraint(
            model_name='sessionpart',
            constraint=models.UniqueConstraint(fields=('session', 'parameter_set_part'), name='unique_session_part'),
        ),
        migrations.AddField(
            model_name='sessionpartperiod',
            name='parameter_set_part_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_part_periods_b', to='main.parametersetpartperiod'),
        ),
        migrations.AddField(
            model_name='sessionpartperiod',
            name='session_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_part_periods_a', to='main.sessionpart'),
        ),
        migrations.AddConstraint(
            model_name='sessionpartperiod',
            constraint=models.UniqueConstraint(fields=('session_part', 'parameter_set_part_period'), name='unique_session_part_period'),
        ),
    ]
