# Generated by Django 4.0.8 on 2022-10-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_sessionpartperiod_alter_sessionpart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerpart',
            name='parameter_set_player_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_parts_c', to='main.parametersetplayerpart'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='parameter_set_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_players_b', to='main.parametersetplayer'),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_players_a', to='main.session'),
        ),
        migrations.AlterField(
            model_name='sessionplayerpart',
            name='earnings',
            field=models.IntegerField(default=0, verbose_name='Part Earnings'),
        ),
        migrations.CreateModel(
            name='SessionPlayerPartPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.IntegerField(default=0, verbose_name='Period Earnings')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_part_periods_c', to='main.parametersetrandomoutcome')),
                ('parameter_set_labels_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_part_periods_b', to='main.parametersetlabelsperiod')),
                ('session_player_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_part_periods_a', to='main.sessionplayerpart')),
            ],
            options={
                'verbose_name': 'Session Player Part Period',
                'verbose_name_plural': 'Session Player Part Periods',
                'ordering': ['session_player_part', 'parameter_set_labels_period'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionplayerpartperiod',
            constraint=models.UniqueConstraint(fields=('session_player_part', 'parameter_set_labels_period'), name='unique_session_player_period_part'),
        ),
    ]
