# Generated by Django 4.0.8 on 2022-10-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_sessionplayerpart_parameter_set_player_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current_period',
        ),
        migrations.AddField(
            model_name='session',
            name='current_part',
            field=models.ForeignKey(blank=b'I01\n', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_c', to='main.sessionpart'),
        ),
    ]
