# Generated by Django 4.0.8 on 2022-10-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_sessionpart_current_part_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerpartperiod',
            name='session_part_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_part_periods_d', to='main.sessionpartperiod'),
        ),
    ]
