# Generated by Django 4.0.8 on 2022-10-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_sessionplayerpartperiod_session_part_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionpart',
            old_name='current_part_period',
            new_name='current_session_part_period',
        ),
    ]
