# Generated by Django 4.0.8 on 2022-10-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_current_part_period_sessionpart_current_session_part_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='current_part',
            new_name='current_session_part',
        ),
    ]
