# Generated by Django 4.1.2 on 2022-10-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_results_shown_sessionpart_show_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpartperiod',
            name='majority_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_part_periods_c', to='main.parametersetrandomoutcome'),
        ),
        migrations.AlterField(
            model_name='sessionpart',
            name='show_results',
            field=models.BooleanField(default=False, verbose_name='Shown results to subject'),
        ),
    ]
