# Generated by Django 4.1.2 on 2022-10-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_sessionpartperiod_majority_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerpartperiod',
            name='majority_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_player_part_periods_e', to='main.parametersetrandomoutcome'),
        ),
    ]
