# Generated by Django 4.1.2 on 2022-10-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_sessionplayerpartperiod_majority_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionpartperiod',
            name='majority_choice',
        ),
    ]
