# Generated by Django 4.1.2 on 2022-10-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_sessionpartperiod_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayerchat',
            old_name='session_period',
            new_name='session_part',
        ),
    ]
