# Generated by Django 4.1.2 on 2022-10-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_session_period_sessionplayerchat_session_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplayerpartperiod',
            name='earnings',
        ),
    ]
