# Generated by Django 4.1.2 on 2022-10-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_session_current_experiment_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='instruction_set',
        ),
        migrations.AddField(
            model_name='parametersetpart',
            name='instruction_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_parts_b', to='main.instructionset'),
            preserve_default=False,
        ),
    ]
