# Generated by Django 4.1.2 on 2022-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_parameterset_instruction_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplayer',
            name='current_instruction',
        ),
        migrations.RemoveField(
            model_name='sessionplayer',
            name='current_instruction_complete',
        ),
        migrations.RemoveField(
            model_name='sessionplayer',
            name='instructions_finished',
        ),
        migrations.AddField(
            model_name='sessionplayerpart',
            name='current_instruction',
            field=models.IntegerField(default=0, verbose_name='Current Instruction'),
        ),
        migrations.AddField(
            model_name='sessionplayerpart',
            name='current_instruction_complete',
            field=models.IntegerField(default=0, verbose_name='Current Instruction Complete'),
        ),
        migrations.AddField(
            model_name='sessionplayerpart',
            name='instructions_finished',
            field=models.BooleanField(default=False, verbose_name='Instructions Finished'),
        ),
    ]
