# Generated by Django 4.1.2 on 2022-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_sessionplayerpartperiod_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='period_length',
            field=models.IntegerField(default=10, verbose_name='Period Length, Production'),
        ),
    ]
