# Generated by Django 4.1.2 on 2022-11-04 21:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_result_sessionplayer_status_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='parameter_set_json',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
