# Generated by Django 4.1.2 on 2022-11-04 21:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_session_parameter_set_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='parameter_set_json_for_subject',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
