# Generated by Django 4.1.2 on 2022-11-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_session_parameter_set_json_for_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayer',
            old_name='status_json',
            new_name='session_player_parts_json',
        ),
    ]
