# Generated by Django 4.1.2 on 2022-11-07 03:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_rename_status_json_sessionplayer_session_player_parts_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayerpartperiod',
            name='json_for_group_json',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
