# Generated by Django 4.1.2 on 2022-11-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_sessionplayerpartperiod_json_for_group_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='survey_link',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Survey Link'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='survey_required',
            field=models.BooleanField(default=False, verbose_name='Survey Required'),
        ),
        migrations.AddField(
            model_name='sessionplayer',
            name='survey_complete',
            field=models.BooleanField(default=False, verbose_name='Survey Complete'),
        ),
    ]
