# Generated by Django 4.1.2 on 2022-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_parameterset_survey_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='survey_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Survey Link'),
        ),
    ]
