# Generated by Django 4.1.2 on 2022-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_parameterset_survey_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetrandomoutcome',
            name='label',
            field=models.CharField(default='abc.jpg', max_length=100),
        ),
    ]
