# Generated by Django 4.1.2 on 2022-11-21 16:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_sessionplayerpartperiod_choice_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionplayerpart',
            options={'ordering': ['session_player', 'session_part__parameter_set_part__part_number'], 'verbose_name': 'Session Player Part', 'verbose_name_plural': 'Session Player Part'},
        ),
        migrations.AddField(
            model_name='sessionplayerpartperiod',
            name='indexes_json',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
