# Generated by Django 4.1.2 on 2022-11-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_sessionplayerpart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
    ]
