# Generated by Django 4.1.2 on 2022-11-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_parametersetplayer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_d', to='main.parameterset'),
        ),
    ]
