# Generated by Django 4.1.2 on 2022-11-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_session_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='player_number',
            field=models.IntegerField(default=0, verbose_name='Player number'),
        ),
    ]
