# Generated by Django 4.1.2 on 2022-11-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_parametersetplayer_player_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetplayer',
            options={'ordering': ['player_number'], 'verbose_name': 'Parameter Set Player', 'verbose_name_plural': 'Parameter Set Players'},
        ),
    ]
